AccountingApp/Entities/BaseEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AccountingApp.Entities
{
    public abstract class BaseEntity
    {
    }
}

AccountingApp/Entities/DetaliiFactura.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AccountingApp.Entities
{
    public class DetaliiFactura: BaseEntity
    {
        public int IdDetaliiFactura { get; set; }
        public int IdLocatie { get; set; }
        [Column(TypeName = "int")]
        public int IdFactura { get; set; }
        [Column(TypeName = "nvarchar(100)")]
        public string NumeProdus { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal Cantitate { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal PretUnitar { get; set; }
        [Column(TypeName = "decimal(18,2)")]
        public decimal Valoare { get; set; }
    }
}

AccountingApp/Entities/Facturi.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace AccountingApp.Entities
{
    public class Facturi: BaseEntity
    {
        public int IdFactura { get; set; }
        public int IdLocatie { get; set; }
        [Column(TypeName = "nvarchar(100)")]
        public string NumarFactura { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DataFactura { get; set; }
        [Column(TypeName = "nvarchar(100)")]
        public string NumeClient { get; set; }
    }
}

AccountingApp/Models/DetaliiFacturaReadOrCreate.cs
using AccountingApp.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AccountingApp.Models
{
    public class DetaliiFacturaReadOrCreate
    {
        public int IdDetaliiFactura { get; set; }
        [Range(1, int.MaxValue, ErrorMessage = "Please enter a value bigger than {1}")]
        public int IdLocatie { get; set; }

        public int IdFactura { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string NumeProdus { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public decimal Cantitate { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public decimal PretUnitar { get; set; }

        public decimal Valoare { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string NumeClient { get; set; }
        [Required(ErrorMessage = "This field is required")]
        public string NumarFactura { get; set; }
    }
}

AccountingApp/Models/ErrorViewModel.cs
using System;

namespace AccountingApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AccountingApp/Models/FacturiDinGrid.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AccountingApp.Models
{
    public class FacturiDinGrid
    {
        public int IdFactura { get; set; }
        public int IdLocatie { get; set; }
        public string NumarFactura { get; set; }
        public DateTime DataFactura { get; set; }
        public string NumeClient { get; set; }
        public string NumeProdus { get; set; }
        public decimal Cantitate { get; set; }
        public decimal PretUnitar { get; set; }
        public decimal Valoare { get; set; }
    }
}

AccountingApp/Controllers/FacturiController.cs
using AccountingApp.Context;
using AccountingApp.Models;
using AccountingApp.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AccountingApp.Services;

namespace AccountingApp.Controllers
{
    public class FacturiController : Controller
    {
        private readonly FacturiService _facturiService;

        public FacturiController(FacturiService facturiService)
        {
            _facturiService = facturiService;
        }
        public IActionResult Index()
        {
            return View(_facturiService.ReturnDataToGrid());
        }
        public IActionResult AddOrEdit(int idFactura = 0,int idLocatie=0)
        {
            if (idFactura == 0)
                return View(new DetaliiFacturaReadOrCreate());
            else
            {
                return View(_facturiService.ReturnDataToEdit(idFactura, idLocatie));
            }               
        }

        [HttpPost]
        public IActionResult AddorEdit([Bind("IdFactura,IdLocatie,NumarFactura,NumeClient,NumeProdus,Cantitate,PretUnitar")] DetaliiFacturaReadOrCreate detaliiFactura)
        {
            if (ModelState.IsValid)
            {
                if (detaliiFactura.IdFactura == 0)
                {
                    _facturiService.Insert(detaliiFactura);
                }
                else
                {
                    _facturiService.Update(detaliiFactura);
                }

                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        public IActionResult Delete(int idFactura, int idLocatie)
        {
            _facturiService.Delete(idFactura,idLocatie);
            return RedirectToAction(nameof(Index));
        }

    }
}

AccountingApp/Controllers/HomeController.cs
using AccountingApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AccountingApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

AccountingApp/Views/Facturi/AddOrEdit.cshtml
@model DetaliiFacturaReadOrCreate
@{
    ViewData["Title"] = "Create";
}

<h4>Formular adaugare factura</h4>
<hr />
<div class="col-md-6">
    <form asp-action="AddorEdit">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="IdFactura" />
        <div class="form-group">
            <label asp-for="IdLocatie" class="control-label"></label>
            <input asp-for="IdLocatie" class="form-control" />
            <span asp-validation-for="IdLocatie" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="NumarFactura" class="control-label"></label>
            <input asp-for="NumarFactura" class="form-control" />
            <span asp-validation-for="NumarFactura" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="NumeClient" class="control-label"></label>
            <input asp-for="NumeClient" class="form-control" />
            <span asp-validation-for="NumeClient" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="NumeProdus" class="control-label"></label>
            <input asp-for="NumeProdus" class="form-control" />
            <span asp-validation-for="NumeProdus" class="text-danger"></span>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <label asp-for="Cantitate" class="control-label"></label>
                <input asp-for="Cantitate" class="form-control" />
                <span asp-validation-for="Cantitate" class="text-danger"></span>
            </div>
            <div class="form-group col-md-6">
                <label asp-for="PretUnitar" class="control-label"></label>
                <input asp-for="PretUnitar" class="form-control" />
                <span asp-validation-for="PretUnitar" class="text-danger"></span>
            </div>
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <input type="submit" value="Submit" class="btn btn-secondary btn-block" />
            </div>
            <div class="form-group col-md-6">
                <a asp-action="Index" class="btn btn-secondary btn-block"><i class="fa fa-table"></i> Back to List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AccountingApp/Views/Facturi/Index.cshtml
@model IEnumerable<FacturiDinGrid>
@{
    ViewData["Title"] = "Index";
}

<h1>Facturi din system</h1>
<p><a asp-action="AddOrEdit" class="btn btn-outline-success"><i class="fa fa-plus-square"></i> Adauga factura</a></p>
<table>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdFactura)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdLocatie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumarFactura)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataFactura)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeClient)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumeProdus)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cantitate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PretUnitar)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Valoare)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdFactura)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdLocatie)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumarFactura)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataFactura)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeClient)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumeProdus)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cantitate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PretUnitar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Valoare)
            </td>
            <td>
                <a asp-action="AddOrEdit" asp-route-idFactura="@item.IdFactura" asp-route-idLocatie="@item.IdLocatie">Edit<i class="fa fa-marker fa-lg"></i></a>
                <a asp-action="Delete" asp-route-idFactura="@item.IdFactura" asp-route-idLocatie="@item.IdLocatie" class="text-danger ml-1" onclick="return confirm('Sunteti sigur ca vreti sa stergeti factura?')">Delete<i class="fa fa-trash-alt fa-lg"></i></a>
            </td>
        </tr>
        }
    </tbody>
</table>

AccountingApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

AccountingApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AccountingApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AccountingApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Facturi" asp-action="Index">Facturi</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AccountingApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>